"""
Unit tests for gateway.py, using moto to mock AWS instead of requiring
floci to be running. Run with: uv run pytest

These deliberately test pure logic and error handling, not the actual
Bedrock/Ollama round trip - that's what the end-to-end curl tests
documented in the tutorial (Schritt 18, 24, 28, 34) are for.
"""
import base64
import json
import os

import boto3
from moto import mock_aws

os.environ.setdefault("REQUEST_LOG_TABLE", "llm-gateway-requests")
os.environ.setdefault("CACHE_TABLE", "llm-gateway-cache")
os.environ.setdefault("CACHE_TTL_SECONDS", "3600")
os.environ.setdefault("AWS_DEFAULT_REGION", "us-east-1")

from gateway import get_cache_key


def test_cache_key_differs_by_model():
    """Same prompt, different model -> different cache key.

    This is the core correctness property of the caching design from
    Schritt 34: without including modelId in the hash, a cache hit could
    return an answer generated by the wrong model.
    """
    key_a = get_cache_key("Hello", "anthropic.claude-3-haiku-20240307-v1:0")
    key_b = get_cache_key("Hello", "anthropic.claude-3-sonnet-20240229-v1:0")
    assert key_a != key_b


def test_cache_key_stable_for_identical_input():
    key_a = get_cache_key("Hello", "anthropic.claude-3-haiku-20240307-v1:0")
    key_b = get_cache_key("Hello", "anthropic.claude-3-haiku-20240307-v1:0")
    assert key_a == key_b


def test_cache_key_differs_by_prompt():
    key_a = get_cache_key("Hello", "anthropic.claude-3-haiku-20240307-v1:0")
    key_b = get_cache_key("Goodbye", "anthropic.claude-3-haiku-20240307-v1:0")
    assert key_a != key_b


@mock_aws
def test_missing_prompt_returns_400():
    from gateway import handler

    event = {"body": json.dumps({})}
    result = handler(event, None)

    assert result["statusCode"] == 400
    assert "prompt" in json.loads(result["body"])["error"]


@mock_aws
def test_base64_encoded_body_is_decoded():
    """Regression test for the exact bug hit during Phase 1 debugging:
    API Gateway Base64-encodes the body when the client doesn't send an
    explicit Content-Type: application/json header, and the handler must
    account for isBase64Encoded rather than assuming a plain JSON string.
    """
    from gateway import handler

    raw_body = json.dumps({"prompt": ""})  # empty prompt -> deterministic 400, no Bedrock call needed
    event = {
        "body": base64.b64encode(raw_body.encode()).decode(),
        "isBase64Encoded": True,
    }
    result = handler(event, None)

    # If base64 decoding didn't happen, json.loads would raise JSONDecodeError
    # before ever reaching the "prompt fehlt" check - so getting a clean 400
    # here proves the body was decoded correctly.
    assert result["statusCode"] == 400


@mock_aws
def test_api_key_prefers_authorizer_context_over_header():
    """The gateway should trust the verified authorizer context over the
    raw header when both are present, since the header alone isn't proof
    the request actually passed the authorizer's checks."""
    dynamodb = boto3.client("dynamodb", region_name="us-east-1")
    dynamodb.create_table(
        TableName=os.environ["CACHE_TABLE"],
        KeySchema=[{"AttributeName": "promptHash", "KeyType": "HASH"}],
        AttributeDefinitions=[{"AttributeName": "promptHash", "AttributeType": "S"}],
        BillingMode="PAY_PER_REQUEST",
    )
    dynamodb.create_table(
        TableName=os.environ["REQUEST_LOG_TABLE"],
        KeySchema=[{"AttributeName": "requestId", "KeyType": "HASH"}],
        AttributeDefinitions=[{"AttributeName": "requestId", "AttributeType": "S"}],
        BillingMode="PAY_PER_REQUEST",
    )

    # We can't easily mock bedrock-runtime's Converse response with moto
    # (Bedrock Runtime data-plane mocking support is limited), so this test
    # only exercises the code path up to the point where the key is read -
    # a fuller integration test belongs in the curl-based test suite.
    from gateway import handler

    event = {
        "body": json.dumps({"prompt": ""}),  # short-circuits at the 400 check
        "requestContext": {"authorizer": {"lambda": {"apiKey": "from-context"}}},
        "headers": {"x-api-key": "from-header"},
    }
    # Not asserting on the (unreachable) logged apiKey here since the request
    # returns 400 before logging - this test exists as a placeholder showing
    # where a fuller assertion would go once Bedrock Runtime mocking matures.
    result = handler(event, None)
    assert result["statusCode"] == 400